#!/bin/bash

BIN=./compress

rm -f .tmp/* > /dev/null

for i in `seq 1 10` ;
do
    if [ ! -f tests/t${i} ];
    then
        break
    fi

    echo -n "Test ${i}: compress "
    t1=`(time ${BIN} -c -i tests/t${i} -o .tmp/compress) 2>&1 | grep -o -e '.m.\....s' -m 1`
    echo -n "decompress "
    t2=`(time ${BIN} -x -i .tmp/compress -o .tmp/decompress) 2>&1 | grep -o -e '.m.\....s' -m 1`
    if ! cmp tests/t${i} .tmp/decompress > /dev/null ; then
        echo " FAILED"
        mv .tmp/compress .tmp/compress.${i}
        mv .tmp/decompress .tmp/decompress.${i}
    else
        echo " OK ( compress: ${t1}; decompress: ${t2}"
    fi
done

echo Tests over
