#!/bin/bash

BIN="./compress -a huffman"

if [ -d .tmp ] ; then
    rm -f .tmp/* > /dev/null
else
    mkdir .tmp
fi

for i in `seq 1 10` ;
do
    if [ ! -f tests/t${i} ];
    then
        break
    fi

    echo -n "Test ${i}: compress "
    t1=`(time ${BIN} -c -i tests/t${i} -o .tmp/compress &> log) 2>&1 | grep -o -Pe '.?.m.?.\....s' -m 1`
    echo -n "decompress "
    t2=`(time ${BIN} -x -i .tmp/compress -o .tmp/decompress &> log1) 2>&1 | grep -o -Pe '.?.m.?.\....s' -m 1`
    if ! cmp tests/t${i} .tmp/decompress > /dev/null ; then
        echo " FAILED ( compress: ${t1}; decompress: ${t2} )"
        mv .tmp/compress .tmp/compress.${i}
        mv .tmp/decompress .tmp/decompress.${i}
        break
    else
        echo " OK ( compress: ${t1}; decompress: ${t2} )"
    fi
done

echo Tests over
