#!/bin/bash

BIN="./compress -a huffman"

if [ -d .tmp ] ; then
    rm -Rf .tmp/* > /dev/null
else
    mkdir .tmp
fi

for i in `seq 1 10` ;
do
    if [ ! -f tests/t${i} ];
    then
        break
    fi

    echo -n "Test ${i}: compress "
    t1=`(time ${BIN} -c -o .tmp/compress tests/t${i} &> log) 2>&1 | grep -o -Pe '.?.m.?.\....s' -m 1`
    echo -n "decompress "
    t2=`(time ${BIN} -x -o .tmp/ .tmp/compress &> log1) 2>&1 | grep -o -Pe '.?.m.?.\....s' -m 1`
    if ! cmp tests/t${i} .tmp/tests/t${i} > /dev/null ; then
        echo " FAILED ( compress: ${t1}; decompress: ${t2} )"
        break
    else
        echo " OK ( compress: ${t1}; decompress: ${t2} )"
    fi
done

echo Tests over
